---
- name: Ensure HAProxy is installed and up to date
  dnf:
    name: haproxy
    state: latest

- name: Create haproxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
    validate: /usr/sbin/haproxy -c -f %s
  notify: restart haproxy

- name: Allow listening on port 6443 and 22623
  community.general.seport:
    ports: 6443,22623
    proto: tcp
    setype: http_port_t
    state: present

- name: Allow traffic
  firewalld:
    port: "{{ item }}/tcp"
    state: enabled
    immediate: true
    permanent: true
  loop: "{{ haproxy_ports }}"
    
- name: Enable and start haproxy
  service:
    name: haproxy
    state: started
    enabled: true
